# Generated by Django 5.1 on 2024-10-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_emprestimo', models.CharField(max_length=100)),
                ('data_emprestimo', models.DateTimeField(auto_now=True)),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
            options={
                'db_table': 'emprestimo',
            },
        ),
    ]
