# Generated by Django 5.1.1 on 2024-10-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emprestimo_condicao_emprestimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='situacao',
        ),
    ]
